[package]
name = "image_to_console"
version = "0.1.13"
edition = "2021"

authors = ["yyxxryrx <yyxxryrx@outlook.com>"]

description = "A high-performance terminal image viewer written in Rust."
license = "MIT"
readme = "../README_zh-CN.md"
homepage = "https://github.com/yyxxryrx/image_to_console"
repository = "https://github.com/yyxxryrx/image_to_console"

keywords = ["image", "terminal", "console", "viewer"]
categories = ["command-line-utilities", "development-tools", "multimedia::images"]

[features]
video = ["ndarray", "video-rs", "ez-ffmpeg"]

[dependencies]
gif = "0.13.3"
rayon = "1.11.0"
rodio = "0.21.1"
image = "0.25.4"
base64 = "0.22.1"
indicatif = "0.17.8"
crossbeam-channel = "0.5.15"

[dependencies.clap]
version = "4.5.20"
features = ["derive"]

[dependencies.reqwest]
version = "0.12.9"
features = ["blocking"]

[dependencies.ez-ffmpeg]
optional = true
version = "0.5.3"

[dependencies.ndarray]
optional = true
version = "0.16.1"

[dependencies.video-rs]
optional = true
version = "0.10.3"
features = ["ndarray"]


[dependencies.image_to_console_core]
path = "../image-to-console-core"
features = ["gif"]