name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-and-upload:
    name: Build & Upload
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: image_to_console-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: image_to_console-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: image_to_console-macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: image_to_console-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install Alsa-sys
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install libasound2-dev pkg-config -y
          fi

      - name: Build
        env:
          OPENSSL_STATIC: 1
        run: cargo build --release --target ${{ matrix.target }} --package image_to_console

      - name: Build Wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          working-directory: "image-to-console-core-python"

      - name: Package
        shell: bash
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/image_to_console${{ matrix.os == 'windows-latest' && '.exe' || '' }} \
             dist/${{ matrix.name }}
          cd dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../${{ matrix.name }}.zip ${{ matrix.name }}
          else
            tar czf ../${{ matrix.name }}.tar.gz ${{ matrix.name }}
          fi

      - name: Upload Python Wheels (bash)
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail

          # 把 Windows 路径中的反斜杠换成斜杠，保证 glob 在 bash 下能匹配
          workspace="${GITHUB_WORKSPACE//\\//}"
          echo "Workspace: $workspace"

          shopt -s nullglob
          wheel_files=("$workspace"/target/wheels/*.whl)

          if (( ${#wheel_files[@]} > 0 )); then
            for wheel in "${wheel_files[@]}"; do
              echo "Uploading wheel: $wheel"
              upload_url=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${GITHUB_REF_NAME}" \
                | jq -r '.upload_url' | sed 's/{?name,label}//')
              curl -sS -X POST \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @"$wheel" \
                "${upload_url}?name=$(basename "$wheel")"
            done
          else
            echo "No wheel files found in $workspace/target/wheels"
            echo "Listing target directory for debugging:"
            ls -la "$workspace"/target || true
          fi
      

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ matrix.name }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_name: ${{ matrix.name }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_content_type: application/octet-stream